### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by jorisvddonk** [jorisvddonk/node-red-contrib-discord#19]
Hey!

When I started `node-red-contrib-discord` a few years ago, I was actively developing Discord bots and discovered node-red, figuring that a set of Discord nodes for node-red would make for a fun side project that would allow me to learn node-red, and hopefully make writing cool bots a little bit more easy for myself and the company I worked for at the time.

I have since moved on (to a different country and to a different job), and no longer actively maintain any Discord bots based on `node-red-contrib-discord`, myself. As such, my involvement with `node-red-contrib-discord` has diminished rather significantly over the years.

At the moment, my maintainership revolves around looking through pull requests when I'm sitting idle at an airport (doesn't happen that often) and going through issues when I'm not working on something else or exploring the beautiful Swedish ~~countryside~~ forests and lakes (_really_ doesn't happen that often).

Looking at the npm stats, it seems that there's a genuine interest in a set of good Discord nodes for node-red. Unfortunately, I cannot give `node-red-contrib-discord` the attention that it needs, and I think it's in the best interest of `node-red-contrib-discord` users and the node-red community if someone else takes over maintainership from me.

If anyone is willing to take over maintainership, I'd be happy to figure out what needs to happen to make it happen. Until then, I'll try to remember to look at the issue and PR list whenever it's rainy outside ;)

Thanks!

**Comment by Kakimoty-Field** [comment]
Hello

Sorry for poor English

I play with discord-bot using node-red-contrib-discord.
It is a very enjoyable time.
Thanks to node-red-contrib-discord.

If possible, I want to use it in the future.
I want to maintain node-red-contrib-discord.

Thanks.

**Comment by jorisvddonk** [comment]
Hi,

Awesome, thanks! That's fantastic news to hear after coming back from a holiday ;) I'll figure out a list of things I'll have to do in order to transfer ownership and maintenance of the project correctly.

**Comment by ozdeadmeat** [comment]
If I had the skills I would love to help develop this.

**Comment by Villhellm** [comment]
Are you still looking for a maintainer? I'd be willing to take the responsibility

**Comment by jorisvddonk** [comment]
Heh, so this never really happened. But it seems that there's some good forks around, like [node-red-contrib-discord-advanced](https://github.com/Markoudstaal/node-red-contrib-discord-advanced).

I've deprecated the project after the release of 5.0.0, and recommend people move over to a maintained fork, instead.
