### ISSUE TITLE
Install does not work / node-red v16

### ISSUE THREAD

**Issue by daschatten** [jorisvddonk/node-red-contrib-discord#3]
26 May 14:16:11 - [warn] ------------------------------------------
26 May 14:17:47 - [info] Installing module: node-red-contrib-discord
26 May 14:18:36 - [warn] Installation of module node-red-contrib-discord failed:
26 May 14:18:36 - [warn] ------------------------------------------
26 May 14:18:36 - [warn] Error: Command failed: npm install --production node-red-contrib-discord
npm WARN peerDependencies The peer dependency bufferutil@^3.0.0 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency erlpack@hammerandchisel/erlpack included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency node-opus@^0.2.5 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency opusscript@^0.0.3 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sodium@^2.0.1 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency libsodium-wrappers@^0.5.1 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency uws@^0.14.1 included from discord.js will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
prebuild-install info begin Prebuild-install version 2.1.2
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.0-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.0-bufferutil-v3.0.0-node-v48-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /root/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.0-bufferutil-v3.0.0-node-v48-linux-x64.tar.gz
prebuild-install info unpack resolved to /root/.node-red/node_modules/node-red-contrib-discord/node_modules/bufferutil/build/Release/bufferutil.node
prebuild-install info unpack required /root/.node-red/node_modules/node-red-contrib-discord/node_modules/bufferutil/build/Release/bufferutil.node successfully
prebuild-install info install Prebuild successfully installed!
npm WARN cannot run in wd ref@1.3.4 node-gyp rebuild (wd=/root/.node-red/node_modules/node-red-contrib-discord/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref)
../deps/opus/silk/NLSF2A.c: In function ‘silk_NLSF2A’:
../deps/opus/silk/NLSF2A.c:121:17: warning: array subscript is above array bounds [-Warray-bounds]
         Ptmp = P[ k+1 ] + P[ k ];
                 ^
../deps/opus/silk/NLSF2A.c:122:17: warning: array subscript is above array bounds [-Warray-bounds]
         Qtmp = Q[ k+1 ] - Q[ k ];
                 ^
../deps/opus/silk/NLSF2A.c:121:17: warning: array subscript is above array bounds [-Warray-bounds]
         Ptmp = P[ k+1 ] + P[ k ];
                 ^
../deps/opus/silk/NLSF2A.c:122:17: warning: array subscript is above array bounds [-Warray-bounds]
         Qtmp = Q[ k+1 ] - Q[ k ];
                 ^
/root/.node-red/node_modules/node-red-contrib-discord/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/root/.node-red/node_modules/node-red-contrib-discord/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "--production" "node-red-contrib-discord"
npm ERR! node v6.10.3
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE

npm ERR! sodium@2.0.1 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.1 preinstall script 'node install.js --preinstall'.
npm ERR! This is most likely a problem with the sodium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js --preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sodium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log

**Comment by jorisvddonk** [comment]
`sodium` is an optional peerDependency for `discord.js`. The functionality provided by `sodium` isn't used by `node-red-contrib-discord`. You're running an old version of npm (v2) which still installs optional peerdependencies. In npm version 3 or higher, these peer dependencies will not be installed automatically. 

You should upgrade to a newer version of npm (v3 or higher).

**Comment by jorisvddonk** [comment]
Also note that if you upgrade to NPM version 5, you might have to install `node-red-contrib-discord` using the following command inside the `~/.node-red` folder: `npm install --production node-red-contrib-discord .`
